set_property IOSTANDARD LVCMOS33 [get_ports {mclk[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mclk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sclk[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sclk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ws[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ws[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports sd_rx]
set_property IOSTANDARD LVCMOS33 [get_ports sd_tx]
# R2 es SW15
#set_property PACKAGE_PIN R2 [get_ports reset_n]
set_property PACKAGE_PIN G3 [get_ports sd_rx]
set_property PACKAGE_PIN G2 [get_ports sd_tx]
set_property PACKAGE_PIN J1 [get_ports {mclk[1]}]
set_property PACKAGE_PIN H1 [get_ports {mclk[0]}]
set_property PACKAGE_PIN J2 [get_ports {sclk[1]}]
set_property PACKAGE_PIN H2 [get_ports {sclk[0]}]
set_property PACKAGE_PIN L2 [get_ports {ws[1]}]
set_property PACKAGE_PIN K2 [get_ports {ws[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property PACKAGE_PIN W5 [get_ports clock]

#set_property PACKAGE_PIN T1 [get_ports datasw[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports {datasw[3]}]
#set_property PACKAGE_PIN U1 [get_ports datasw[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports {datasw[2]}]
#set_property PACKAGE_PIN W2 [get_ports datasw[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports {datasw[1]}]
#set_property PACKAGE_PIN R3 [get_ports datasw[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports {datasw[0]}]

##################
# UART
##################
set_property PACKAGE_PIN V17 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property PACKAGE_PIN U16 [get_ports {data_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {data_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {data_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {data_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {data_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {data_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {data_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[0]}]
set_property PACKAGE_PIN A18 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN B18 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
# T18 es BTNU - apaga los LEDs
set_property PACKAGE_PIN T18 [get_ports reset_btn]
set_property IOSTANDARD LVCMOS33 [get_ports reset_btn]
#set_property PACKAGE_PIN U18 [get_ports tx_start]
#set_property IOSTANDARD LVCMOS33 [get_ports tx_start]

#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]

# U18 es BTNC - enviar datos uart
set_property PACKAGE_PIN U18 [get_ports tx_enable]
set_property IOSTANDARD LVCMOS33 [get_ports tx_enable]

#create_clock -period 10.000 -name clock -waveform {0.000 5.000} [get_ports clock]
